/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SonevidaRouteImport } from './routes/sonevida'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'

const SonevidaRoute = SonevidaRouteImport.update({
  id: '/sonevida',
  path: '/sonevida',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/galeria': typeof GaleriaRoute
  '/sobre': typeof SobreRoute
  '/sonevida': typeof SonevidaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/galeria': typeof GaleriaRoute
  '/sobre': typeof SobreRoute
  '/sonevida': typeof SonevidaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/galeria': typeof GaleriaRoute
  '/sobre': typeof SobreRoute
  '/sonevida': typeof SonevidaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/galeria' | '/sobre' | '/sonevida'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/galeria' | '/sobre' | '/sonevida'
  id: '__root__' | '/' | '/blog' | '/galeria' | '/sobre' | '/sonevida'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  GaleriaRoute: typeof GaleriaRoute
  SobreRoute: typeof SobreRoute
  SonevidaRoute: typeof SonevidaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sonevida': {
      id: '/sonevida'
      path: '/sonevida'
      fullPath: '/sonevida'
      preLoaderRoute: typeof SonevidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  GaleriaRoute: GaleriaRoute,
  SobreRoute: SobreRoute,
  SonevidaRoute: SonevidaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
